{
 "title": "Redis Queue",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Redis health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "redis_health{instance=\"web:5000\"}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "queue_size" }
   ]
  },
  {
   "title": "Queue operations count by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pop_invocations_total{instance=\"web:5000\"}"
    },
    {
     "expr": "push_invocations_total{instance=\"web:5000\"}"
    },
    {
     "expr": "count_invocations_total{instance=\"web:5000\"}"
    }
   ]
  },
  {
   "title": "Messages in queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "queue_size{instance=\"web:5000\"}"
    }
   ]
  }
 ]
}