version: '3'
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5050:5000"
    depends_on:
      - redis
    volumes:
      - ./config.ini:/app/config.ini  # Mount the config file into the container
  webapp:
    build:
      context: ./app-test
      dockerfile: Dockerfile
    ports:
      - 8080:80
  redis:
    image: "redis:alpine"
  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./prometheus-provisioning/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:8.3.3
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
